name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'widgets/lido'

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 
        working-directory: ./widgets/lido
        run: |
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: widgets/lido/dist
          target-folder: lido